---
name: Docker Image CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get artifacts
        id: artifacts
        run: echo ::set-output name=NEEDED::$(curl -s -L api.github.com/repos/${{ github.repository }}/actions/artifacts | jq -r '.artifacts[].name' | grep -q mesos-built-${{ github.sha }} && echo 0 || echo 1)
      - uses: actions/checkout@v2
        if: steps.artifacts.outputs.NEEDED
      - name: Build the Docker image
        if: steps.artifacts.outputs.NEEDED
        run: curl https://raw.githubusercontent.com/criteo/mesosbuild/master/Dockerfile.automake |
          docker build .
          --file -
          --tag mesosbuild:"$GITHUB_SHA"
          --target builder
          --build-arg CONFIGURE_EXTRA_FLAGS="--enable-test-only-regression"
      #- name: Test mesos
      #  if: steps.artifacts.outputs.NEEDED
      #  run: docker run
      #    -e GTEST_FILTER='-EnvironmentSecretIsolatorTest.*:ExamplesTest.DiskFullFramework:ContainerizerTest.ROOT_CGROUPS_BalloonFramework:ResourceOffersTest.ResourceOfferWithMultipleSlaves'
      #    mesosbuild:"$GITHUB_SHA"
      #    make check -j $(nproc)
      - name: Save the build in tarball
        if: steps.artifacts.outputs.NEEDED
        run: |
          id=$(docker create mesosbuild:"$GITHUB_SHA")
          docker cp $id:/src/mesos - | gzip > mesos-built-${{ github.sha }}.tar.gz
      - name: Upload the built tarball
        if: steps.artifacts.outputs.NEEDED
        uses: actions/upload-artifact@v1
        with:
          name: mesos-built-${{ github.sha }}
          path: mesos-built-${{ github.sha }}.tar.gz
  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f3- | tr '/' '_')
      - name: Download mesos-build
        uses: actions/download-artifact@v1
        with:
          name: mesos-built-${{ github.sha }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: mesos-built-${{ github.sha }}/mesos-built-${{ github.sha }}.tar.gz
          asset_name: mesos-built-${{ steps.get_version.outputs.VERSION }}.tar.gz
          asset_content_type: application/tar+gzip
